### PR TITLE
Refactor: avoid waiting in tests

### PR DESCRIPTION
**Pull request by bershanskiy**
Migrate from `waitForTimeout` to `waitForFunction`. This speeds up tests by 25% on my machine, I think greater speedups can be achieved by making `waitForFunction` run more frequently, but I didn't want to tamper with this option just yet.

### CODE REVIEW

**Comment by prushforth** [comment]
I wasn't able to realize a speed up on my machine: 39s vs 40s.  It did say we should consider splitting up render.test.js to improve parallelism, but that seems unrelated to this waiting business.

**Comment by bershanskiy** [comment]
Interesting, on Windows 11 when I run `time npm run test` I get:
Current `main` commit `2a09945cf4ab3b1ae452edc4da1cdcd6b7c507f5`
```
real    0m22.179s
user    0m0.061s
sys     0m0.166s
```
After this patch, commit `8d0afe032e23aa5684a01bd557cc3fcb87f7402e`:
```
real    0m16.598s
user    0m0.060s
sys     0m0.184s
```

**Comment by bershanskiy** [comment]
One possible problem with the tests which might explain why they take whole 40 seconds on your machine: some tests are network-dependent so perhaps your internet impacts them. Ideally, we should make them offline or at least use a local file cache (download once on first test invocation and then reuse) to avoid spamming real sites.

**Comment by prushforth** [comment]
Well, regardless of whether or not I observe a speedup, the code is more meaningful with the suggested improvements, and we should follow this style.  Thanks!

**Comment by prushforth** [comment]
>  Ideally, we should make them offline or at least use a local file cache (download once on first test invocation and then reuse) to avoid spamming real sites.

Agreed.

**Pull request merged**
