### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by bershanskiy**
- Upgrade `jest`, `jest-playwright-preset`, and `playwright`
 - Remove [npmjs.org `path` dependency](https://www.npmjs.com/package/path) and use the standard, newer NodeJS one. (NPM just has a NodeJS version from 7 years ago.)

### CODE REVIEW

**Comment by prushforth** [comment]
@ben-lu-uw was going to ask you what you think but we are hoping to get rid of jest as the test runner, replace with playwright.

**Comment by bershanskiy** [comment]
> we are hoping to get rid of jest as the test runner, replace with playwright.

Looks like you already migrated to Playwright, so this might be late: I have never used Playwright myself, but I'm cautiously optimistic about it (because it does address some limitations of Jest). I'm glad for a chance to use it on a smaller project like this before I I attempt to migrate other projects I work on. :)

**Comment by prushforth** [comment]
>  I'm glad for a chance to use it on a smaller project like this before I I attempt to migrate other projects I work on.

We are experiencing flaky tests in web-map-custom-element, and I believe it may be due to jest, but that is just a hunch.  So we wanted to try this to see what's involved in migrating to playwright test runner, before doing that on the bigger project.

**Comment by bershanskiy** [comment]
I'm seeing some flakes on current `master` which is `2381be79d4e8a17b686cb6b4dd712771c9f57e33`.

**Pull request merged**
