### PR TITLE
Remove "Clear Storage" button from options

### LINKED ISSUE #34: Clearing storage leads to a different internal state than after first install
There is a slight discrepancy between extension `options` right after first install and after storage reset. Specifically:

On first install (inside of `chrome.runtime.onInstalled` listener) extension sets `options` to `{renderMap: true}`:
https://github.com/Maps4HTML/mapml-extension/blob/badce0964af89dd9cbb62b86fbeb11751e5c867f/src/background.js#L46
But the popup/settings UI just clears the storage entirely in `resetStorage()`:
https://github.com/Maps4HTML/mapml-extension/blob/badce0964af89dd9cbb62b86fbeb11751e5c867f/src/popup.js#L51

This means that the following scenario is possible once extension is released on some extension store:
1. User installs extension for the first time and has `renderMap` option enabled
2. User clears storage (removing `options`) and gets `renderMap` option disabled and uses extension for a while
3. Extension gets updated, `chrome.runtime.onInstalled` listener is called, sees that `options` are not there, populates them with default enabling `renderMap`.

This leads to change in settings upon update (which is invisible to user), which can be considered a bug.

### PR DESCRIPTION
**Pull request by bershanskiy**
Fixes #34, related to #27.

### CODE REVIEW

**Comment by ben-lu-uw** [comment]
Made a PR to fix the tests if you need it https://github.com/bershanskiy/mapml-extension/pull/1

**Comment by bershanskiy** [comment]
Thanks a lot, found [another flake](https://github.com/Maps4HTML/mapml-extension/pull/40/commits/17499fcacea747d1ca260ac881b20a1060e2e395) on `main` and I think we can fix it up in this PR as well.

**Comment by prushforth** [comment]
Great, thank you!

**Comment by Genericreqd** [comment]
Maps4HTML

**Pull request merged**
